package AnalizadorLexico;
public enum ClaseLexica 
{
	IDEN, ENT, REAL, PAP, PCIERRE, IGUAL, PCOMA,SEPARADOR,AND,OR,NOT,LT,LE,GE,GT,NEQ,
	MAS, MENOS, POR, DIV, ASIGNACION, EOF, FALSE,TRUE, TREAL,TBOOL,TINT
}
