
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 03 22:22:36 CEST 2020
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PAPER = 2;
  public static final int MENOS = 16;
  public static final int AND = 12;
  public static final int LT = 5;
  public static final int NE = 9;
  public static final int OR = 13;
  public static final int NOT = 14;
  public static final int IDEN = 25;
  public static final int TRUE = 21;
  public static final int PCIE = 3;
  public static final int GT = 8;
  public static final int POR = 17;
  public static final int LE = 6;
  public static final int TENT = 24;
  public static final int SEPARADOR = 11;
  public static final int EOF = 0;
  public static final int TBOOL = 23;
  public static final int DIV = 18;
  public static final int FALSE = 20;
  public static final int GE = 7;
  public static final int TREAL = 22;
  public static final int error = 1;
  public static final int EQ = 4;
  public static final int PCOMA = 10;
  public static final int REAL = 27;
  public static final int ENT = 26;
  public static final int ASIG = 19;
  public static final int MAS = 15;
}

