/* Generated By:JavaCC: Do not edit this line. ConstructorASTCoreConstants.java */
package constructorast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTCoreConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int trueFalse = 8;
  /** RegularExpression Id. */
  int Boolean = 9;
  /** RegularExpression Id. */
  int Int = 10;
  /** RegularExpression Id. */
  int Real = 11;
  /** RegularExpression Id. */
  int identificador = 12;
  /** RegularExpression Id. */
  int numeroEntero = 13;
  /** RegularExpression Id. */
  int numeroReal = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<trueFalse>",
    "\"Boolean\"",
    "\"Int\"",
    "\"Real\"",
    "<identificador>",
    "<numeroEntero>",
    "<numeroReal>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"Not\"",
    "\"(\"",
    "\")\"",
    "\"and\"",
    "\"or\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"*\"",
    "\"/\"",
  };

}
